### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by nolimitdev** [eset-la/Check-EternalBlue#1]
On fully updated Windows 7 SP1 a Windows Server 2008R2 it still says "Your computer is NOT patched against EternalBlue"

**Comment by cpuodzius** [comment]
Hi @nolimitdev ,

Can you please share the list of installed KBs on these system?

You can either fetch this list using:

 * Command prompt: "wmic qfe list"
  * PowerShell: Get-HotFix

**Comment by nolimitdev** [comment]
According to https://technet.microsoft.com/en-us/library/security/ms17-010.aspx bug was originally fixed in KB4012212 (Security Only) or KB4012215 (Monthly Rollup - March, 2017).

According to https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=e138ff63-7614-44e4-b6e4-37fc3df1e482 KB4012215 has been replaced by KB4015549 (Monthly Rollup - April, 2017).

According to https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=c5fc51cf-4111-4218-8ca4-965395c80e62 KB4015549 has been replaced by KB4019264  (Monthly Rollup - 2017-05).

Finally when you check list of included KBs of latest monthly rollup KB4019264 https://support.microsoft.com/en-us/help/4019264/windows-7-update-kb4019264 you can see both KB4012212 and KB4012215.

So if you have installed one of the mentioned KBs you are not vulnerable to EternalBlue. It is enough to have installed newest one KB4019264. VerifyEternalBlue.vbs does not check KB4015549 and KB4019264 and causes false positive result.

**Comment by bontchev** [comment]
Confirmed, Win7 Pro SP1 here, and the script says that the system is not patched, which is false. None of the KBs the script is checking for is installed, but KB4019264 _is_ installed. Neither KB4015549, nor KB4012212, nor KB4012215 are installed.

**Comment by bontchev** [comment]
The list of KB entries the script is checking definitely needs fixing. To begin with, I see no reason why the following are checked:

KB4013429
KB4016635
KB4016636
KB4016637

However, the script should be checking (it currently isn't) for the presence of the following KB entries; any of which would indicate that the system has been patched against MS017-010:

KB4015549
KB4015550
KB4015551
KB4019215
KB4019216
KB4019264
KB4019473
KB4019474

For reference, see slide No. 8 in [Microsoft's presentation on this subject](https://static.spiceworks.com/attachments/post/0017/5996/CustomerReady_WannaCrypt_Guidance.pdf).

Also, the script shelling to cmd.exe to run wmic is just plain stupid and reminds me of the antics some malware does. Well, at least you aren't shelling to PowerShell too. This should be implemented in pure VBScript, using GetObject to obtains a handle to WMI, and then enumerate the installed patches, instead of going through the clipboard, jeez!

Aw, shucks, it would probably be easier to write my own script at this point...

**Comment by cpuodzius** [comment]
Hi @bontchev ,

Awesome reference! It puts together the list of KBs and I'll update the script right away.

It worth mentioning that the script is [prior](https://github.com/puodzius/Check-EternalBlue/commit/93da386006bb7495fe303802fcec5d5da59ca5a6) to this list.

Regarding your own script, let us know about your Columbus' Egg when it is done!

**Comment by cpuodzius** [comment]
Hi @nolimitdev ,

Thank you for your feedback.

It became clear that Windows 10's rollout model is not friendly enough to this verification strategy.
We just released a [tool](https://help.eset.com/eset_tools/ESETEternalBlueChecker.exe) that verifies if the affected component is in a patched version.

I'll keep the repository for historical purposes only, but I won't be updating KBs list anymore.

**Comment by bontchev** [comment]
@puodzius, you are right - the stupid monthly roll-ups mean that such a script would have to be updated every month with new KB entries added to it, so it makes no sense to do the check like this. As for doing it in pure VBScript with no shelling to `cmd.exe` and `wmic.exe` and going through the clipboard, I had in mind something like this:

```
If WScript.Arguments.Count > 1 Then
	WScript.Echo "Usage: " & WScript.Arguments.Item(0) & " [machine]"
	WScript.Quit
End If

If WScript.Arguments.Count = 1 Then
	strPC = WScript.Arguments.Item(0)
Else
	Set objShell = CreateObject("WScript.Shell")
	strPC = objShell.ExpandEnvironmentStrings("%COMPUTERNAME%")
End If

If strPC = "" Then WScript.Quit
If Reachable(strPC) = False Then
	WScript.Echo "Error connecting to " & strPC
	WScript.Quit
End If

Dim MS017_010_KBs
MS017_010_KBs = Array( _
	"KB4012212", _
	"KB4012213", _
	"KB4012214", _
	"KB4012215", _
	"KB4012216", _
	"KB4012217", _
	"KB4012598", _
	"KB4012606", _
	"KB4013198", _
	"KB4015217", _
	"KB4015219", _
	"KB4015221", _
	"KB4015438", _
	"KB4015549", _
	"KB4015550", _
	"KB4015551", _
	"KB4019215", _
	"KB4019216", _
	"KB4019264", _
	"KB4019472", _
	"KB4019473", _
	"KB4019474" _
)

Set objWMIService = GetObject("winmgmts:" & "{impersonationLevel=impersonate}!\\" & strPC & "\root\cimv2")
Set colQuickFixes = objWMIService.ExecQuery("Select * from Win32_QuickFixEngineering")

For Each objItem in colQuickFixes
	strHotfixID = objItem.HotFixID
	If strHotfixID <> "File 1" Then
		For Each KBName in MS017_010_KBs
			If KBName = strHotfixID Then
				WScript.Echo "The machine " & strPC & " is patched against EternalBlue (" & strHotfixID & ")."
				WScript.Quit
			End If
		Next
	End If
Next

WScript.Echo "The machine " & strPC & " is NOT patched against EternalBlue!"

Function Reachable(strComputer)
	Set objWMIService2 = GetObject("winmgmts:\\.\root\cimv2")
	Set colPing = objWMIService2.ExecQuery("Select * from Win32_PingStatus Where Address = '" & strComputer & "'")
	For Each objItem in colPing
		If IsNull(objItem.StatusCode) Or objItem.Statuscode <> 0 Then
			Reachable = False
		Else
			Reachable = True
		End If
	Next
End Function
```
